version: '3'

services: 

  laravel:
    build: 
      context: ../pratica-laravel
      dockerfile: Dockerfile.prod
    image: lppires/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build: 
     context: ../nginx-proxy-reverso
     dockerfile: Dockerfile.prod
    image: lppires/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge      